# Generated by Django 3.1.7 on 2021-05-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0100_drop_tools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tool_Type',
        ),
    ]
