# Generated by Django 3.1.8 on 2021-05-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0101_enable_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_type',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='test_type',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tool_configuration',
            name='tool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_type', to='dojo.test_type'),
        ),
        migrations.DeleteModel(
            name='Tool_Type',
        ),
    ]
