# Generated by Django 3.1.12 on 2021-06-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0113_endpoint_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_type',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
