apiVersion: v2
appVersion: "2.12.0-dev"
description: A Helm chart for Kubernetes to install DefectDojo
name: defectdojo
version: 1.6.34-dev
icon: https://www.defectdojo.org/img/favicon.ico
maintainers:
  - name: madchap
    email: defectdojo-project@owasp.org
    url: https://github.com/DefectDojo/django-DefectDojo
dependencies:
  - name: mysql
    version: ~8.9.0
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: postgresql
    version: ~10.16.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: postgresql-ha
    version: ~8.6.0
    repository: https://charts.bitnami.com/bitnami
    alias: postgresqlha
    condition: postgresqlha.enabled
  - name: rabbitmq
    version: ~8.31.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: ~15.7.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
