{{- if .Values.extraSecrets -}}
{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-extrasecrets
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
{{- range $key, $value  := .Values.extraSecrets }}
{{ $key | indent 2}}: {{ $value | b64enc }}
{{- end }}
{{- end }}
