name: 'Update Chart.lock'
on:
  pull_request_target:
    branches:
      - dev
    paths:
      - 'helm/defectdojo/**.yaml'
permissions:
  contents: write
jobs:
  update-chart-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bitnami/charts
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          path: charts
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.4.0

      - name: Execute generate new chart.lock
        run: |
          # Using the Github API to detect the files changed as git merge-base stops working when the branch is behind
          # and jitterbit/get-changed-files does not support pull_request_target
          #URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          #files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G "$URL")
          #files_changed="$(echo $files_changed_data | jq -r '.[] | .filename')"
          # Adding || true to avoid "Process exited with code 1" errors
          #charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "helm/[^/]*" | sort | uniq || true)"
          #for chart in ${charts_dirs_changed}; do
          #  echo "Updating README.md for ${chart}"
          #    readme-generator --values "charts/${chart}/values.yaml" --readme "charts/${chart}/README.md" --schema "/tmp/schema.json"
          # done
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency list ./helm/defectdojo
          helm dependency update ./helm/defectdojo
      - name: Push changes
        run: |
          # Push all the changes
          cd charts
          if git status -s | grep helm; then
            git config user.name "DefectDojo"
            git config user.email "defectdojo-project@owasp.org"
            git add . && git commit -am "Update README.md with readme-generator-for-helm" --signoff && git push
          fi
